---
abstract: "adds \"override method => sub {...}\" support to Class::Method::Modifiers"
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Class::Method::ModifiersX::Override
name: Class-Method-ModifiersX-Override
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  Moo: 0
  Role::Tiny: 0
requires:
  Class::Method::Modifiers: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Class-Method-ModifiersX-Override
  homepage: https://metacpan.org/release/Class-Method-ModifiersX-Override
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-class-method-modifiersx-override
version: 0.001
